name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_bloc: ^4.0.0
  meta: ^1.1.6
  equatable: ^0.6.0
  http: ^0.12.1
  flutter_secure_storage: ^3.3.0
  shared_preferences: ^0.5.6
  firebase_core: ^0.4.0+9
  google_sign_in: ^4.1.0
  firebase_auth: ^0.15.0+1
  sqflite:
  path:
  rxdart: ^0.24.1
  content_placeholder: ^0.1.0
  flutter_html: ^1.0.0
  webfeed: ^0.4.2
  timeago: ^2.0.26
  liquid_pull_to_refresh: ^2.0.0
  share: ^0.6.4+3
  url_launcher: ^5.4.11
  flutter_feather_icons: ^1.0.3
  cloud_firestore: ^0.13.7
  arcore_flutter_plugin:
    git:
      url: https://github.com/giandifra/arcore_flutter_plugin.git
  arkit_plugin:
    git:
      url: https://github.com/olexale/arkit_flutter_plugin.git
  camera:
  video_player: ^0.10.0
  path_provider: ^0.5.0
  geolocator:
  latlong: ^0.6.1
  gallery_saver:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/norms.png
    - assets/img/logo.jpeg
    - assets/img/logo.png
    - assets/img/near_location_light.png
    - assets/img/near_location_dark.png
    - assets/earth.jpg
    - assets/earth_augmented_image.jpg
    - assets/square_picture.jpg
    - assets/pittograms/colosseo.png
    - assets/pittograms/palatino.png
    - assets/pittograms/foro_romano.png
    - assets/pittograms/domus_aurea.png
    - assets/ar/AR_image.jpg
    - assets/ar/AR_video.jpg

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 800
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
